
import React, { useState, useEffect, useMemo, useRef } from 'react';
import { useParams, Link, useNavigate, useLocation } from 'react-router-dom';
import type { Ebook, UserData } from '../types';
import type { User } from 'firebase/auth';
import { getEbookById } from '../services/firestoreService';
import { ArrowLeft, ChevronLeft, ChevronRight, Sparkles, Lock, Crown } from 'lucide-react';
import LoadingSpinner from '../components/LoadingSpinner';
import ChapterQuiz from '../components/ChapterQuiz';
import InfoBanner from '../components/InfoBanner';

declare global {
    interface Window {
      MathJax: {
        typesetPromise: (elements?: HTMLElement[]) => Promise<void>;
      };
    }
}

interface EbookViewerPageProps {
    user: User | null;
    userData: UserData | null;
}

// Helper to pre-process content HTML (Duplicated from ReaderPage for consistency)
const processContentHtml = (html: string) => {
    let processed = html;

    // 1. Image styling
    processed = processed.replace(
        /<img (.*?)>/g, 
        '<figure class="my-4"><img referrerpolicy="no-referrer" $1><figcaption class="text-[10px] text-gray-500 text-center mt-1 italic w-full">Image generated by AI</figcaption></figure>'
    );

    // 2. MathJax Safety Fixes
    const fixLatex = (text: string) => {
        try {
            return text.replace(/(?<!\\)%/g, '\\%');
        } catch (e) {
            return text.replace(/([^\\])%/g, '$1\\%');
        }
    };

    processed = processed.replace(/\\\((.*?)\\\)/gs, (_, content) => `\\(${fixLatex(content)}\\)`);
    processed = processed.replace(/\\\[(.*?)\\\]/gs, (_, content) => `\\[${fixLatex(content)}\\]`);

    return processed;
};

const EbookViewerPage: React.FC<EbookViewerPageProps> = ({ user, userData }) => {
    const { ebookId } = useParams<{ ebookId: string }>();
    const navigate = useNavigate();
    const location = useLocation();
    const [ebook, setEbook] = useState<Ebook | null>(null);
    const [loading, setLoading] = useState(true);
    const [currentPage, setCurrentPage] = useState(0);
    const contentRef = useRef<HTMLDivElement>(null);
    const textRendererRef = useRef<HTMLDivElement>(null); 
   
    useEffect(() => {
        const fetchEbook = async () => {
            if (ebookId) {
                const fetchedEbook = await getEbookById(ebookId);
                setEbook(fetchedEbook);
            }
            setLoading(false);
        };
        fetchEbook();
    }, [ebookId]);

    const isProUser = userData?.subscriptionStatus === 'pro' || userData?.subscriptionStatus === 'day_pass';

    useEffect(() => {
        if (ebook && (ebook.accessLevel === 'free' || isProUser)) {
             navigate(`/ebook-reader/${ebook.id}`);
        }
    }, [ebook, isProUser, navigate, ebookId]);


    const pages = useMemo(() => {
        if (!ebook) return [];

        const sortedChapters = ebook.chapters && ebook.chapters.length > 0
            ? [...ebook.chapters].sort((a, b) => a.chapter - b.chapter)
            : [];
        const firstChapter = sortedChapters[0];

        const chapterPreviewPage = firstChapter
            ? [{ 
                type: 'content' as const, 
                title: firstChapter.title, 
                content: processContentHtml(firstChapter.content), 
                questions: firstChapter.questions || [] 
              }]
            : [];

        return [
            { type: 'cover' as const, title: ebook.title, coverImageUrl: ebook.coverImageUrl },
            { type: 'toc' as const, tableOfContents: ebook.tableOfContents },
            ...chapterPreviewPage,
            { type: 'upgrade' as const, accessLevel: ebook.accessLevel }
        ];
    }, [ebook]);


    // Robust MathJax Implementation using Manual Injection
    useEffect(() => {
        const renderAndTypeset = async () => {
            if (pages[currentPage]?.type === 'content' && textRendererRef.current) {
                 textRendererRef.current.innerHTML = pages[currentPage].content;
                 
                 const typeset = async () => {
                    if (window.MathJax && window.MathJax.typesetPromise) {
                        try {
                            await window.MathJax.typesetPromise([textRendererRef.current]);
                            // CLEANUP ERRORS
                            const errors = textRendererRef.current?.querySelectorAll('mjx-merror, .mjx-error');
                            errors?.forEach(err => err.remove());
                        } catch (err) {
                            console.error('MathJax error:', err);
                        }
                    }
                 };

                 typeset();
                 
                 const checkInterval = setInterval(() => {
                    if (window.MathJax?.typesetPromise && textRendererRef.current) {
                        typeset();
                        clearInterval(checkInterval);
                    }
                 }, 100);
                 setTimeout(() => clearInterval(checkInterval), 5000);
            }
        }
        renderAndTypeset();
    }, [currentPage, pages]);


    const handleNextPage = () => {
        if (currentPage < pages.length - 1) {
            setCurrentPage(prev => prev + 1);
        }
    };
    
    const handlePrevPage = () => {
        if (currentPage > 0) {
            setCurrentPage(prev => prev - 1);
        }
    };

    if (loading) {
        return (
            <div className="fixed inset-0 bg-gray-900 flex flex-col items-center justify-center">
              <LoadingSpinner />
              <p className="mt-4 text-gray-400">Loading preview...</p>
            </div>
        );
    }

    if (!ebook || pages.length === 0) {
        return <div className="text-center mt-20">Ebook not found.</div>;
    }

    const currentPageData = pages[currentPage];

    return (
        <div className="fixed inset-0 z-50 bg-gray-900 flex flex-col">
            <header className="flex items-center justify-between p-4 bg-gray-800 text-white shadow-md">
                <button onClick={() => navigate('/')} className="flex items-center space-x-2 text-orange-500">
                    <ArrowLeft size={20}/>
                </button>
                <div className="text-center truncate flex-1 mx-4">
                    <h1 className="font-bold">{ebook.title}</h1>
                </div>
                <div className="w-10"></div>
            </header>

            <main className="flex-grow overflow-y-auto p-4 md:p-8">
                <div className="max-w-3xl w-full mx-auto">
                    {currentPageData.type === 'cover' && (
                        <div className="text-center flex flex-col items-center justify-center min-h-[70vh]">
                            <img src={currentPageData.coverImageUrl} alt={currentPageData.title} className="w-full max-w-sm mx-auto rounded-lg shadow-2xl aspect-square object-cover"/>
                            <h1 className="text-4xl font-bold mt-8">{currentPageData.title}</h1>
                        </div>
                    )}
                    {currentPageData.type === 'toc' && (
                         <div>
                            <h2 className="text-3xl font-bold mb-6 text-orange-500">Table of Contents</h2>
                             <ul className="space-y-2">
                                 {currentPageData.tableOfContents.map(item => <li key={item.chapter} className="text-lg">{item.chapter}. {item.title}</li>)}
                            </ul>
                        </div>
                    )}
                    {currentPageData.type === 'content' && (
                        <div ref={contentRef}>
                            <h2 className="text-3xl font-bold mb-6 text-orange-500">{currentPageData.title}</h2>
                            {/* Manual Injection Container */}
                            <div 
                                className="ebook-content text-lg leading-relaxed text-gray-300" 
                                ref={textRendererRef} 
                            />
                            {currentPageData.questions && currentPageData.questions.length > 0 && (
                                <ChapterQuiz 
                                    questions={currentPageData.questions} 
                                    themeClasses="bg-gray-900 text-gray-100" // Default dark theme for viewer
                                />
                            )}
                        </div>
                    )}
                    {currentPageData.type === 'upgrade' && (
                        <div className="text-center bg-gray-800 p-8 rounded-[2.5rem] border border-gray-700 relative overflow-hidden">
                            <div className="absolute inset-0 bg-gradient-to-br from-orange-600 to-orange-900 opacity-20 blur-3xl"></div>
                            
                            <div className="relative z-10">
                                <div className="bg-yellow-500/20 p-5 rounded-full w-20 h-20 mx-auto flex items-center justify-center mb-6 border border-yellow-500/30">
                                    <Lock size={40} className="text-yellow-500 animate-pulse" />
                                </div>

                                <h2 className="text-2xl font-black text-white mb-4 uppercase tracking-tighter italic">Pro Required</h2>
                                
                                <div className="max-w-xs mx-auto mb-8">
                                    <p className="text-gray-400 text-sm leading-relaxed">
                                        This is a premium academic textbook. To read all <span className="text-white font-bold">{ebook.chapters?.length} chapters</span>, access deep explanations, and complete the full mastery quiz, you need an active Pro plan.
                                    </p>
                                </div>

                                <div className="grid grid-cols-1 gap-3 mb-8">
                                    <div className="bg-gray-900 p-4 rounded-2xl border border-white/5 flex items-center gap-3 text-left">
                                        <div className="bg-orange-600/20 p-2 rounded-xl text-orange-500"><Sparkles size={20}/></div>
                                        <div><p className="text-xs font-bold text-white uppercase">Complete Access</p><p className="text-[10px] text-gray-500">Every book, every chapter.</p></div>
                                    </div>
                                    <div className="bg-gray-900 p-4 rounded-2xl border border-white/5 flex items-center gap-3 text-left">
                                        <div className="bg-blue-600/20 p-2 rounded-xl text-blue-400"><Crown size={20}/></div>
                                        <div><p className="text-xs font-bold text-white uppercase">AI Study Power</p><p className="text-[10px] text-gray-500">Summaries, Definitions, & Audio.</p></div>
                                    </div>
                                </div>
                                
                                <div className="flex flex-col gap-3">
                                    <Link
                                        to="/upgrade"
                                        className="w-full bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-500 hover:to-red-500 text-white font-black py-5 rounded-2xl text-sm uppercase tracking-[0.2em] shadow-2xl transition-all transform hover:scale-[1.02] active:scale-95 flex items-center justify-center gap-2"
                                    >
                                        <Crown size={18} fill="currentColor"/> Go Pro Now
                                    </Link>
                                    <button 
                                        onClick={() => navigate('/')}
                                        className="text-gray-500 hover:text-white text-[10px] font-black uppercase tracking-widest py-2 transition-colors"
                                    >
                                        Return to Mission Control
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            </main>

            <footer className="bg-gray-800 p-4 shadow-inner">
                <div className="flex items-center justify-between max-w-4xl mx-auto">
                    <button onClick={handlePrevPage} disabled={currentPage === 0} className="p-3 rounded-full bg-gray-700 hover:bg-orange-600 disabled:opacity-50 disabled:hover:bg-gray-700 transition-colors">
                        <ChevronLeft />
                    </button>
                    <span className="text-sm text-gray-400">{currentPage + 1} / {pages.length}</span>
                    <button onClick={handleNextPage} disabled={currentPage === pages.length - 1} className="p-3 rounded-full bg-gray-700 hover:bg-orange-600 disabled:opacity-50 disabled:hover:bg-gray-700 transition-colors">
                        <ChevronRight />
                    </button>
                </div>
            </footer>
        </div>
    );
};

export default EbookViewerPage;
